/*
 * Project REST API
 * Generated REST API documentation
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codegen.api;

import com.codegen.ApiException;
import com.codegen.models.EntitiesDynatCategorySearchPostRequest;
import com.codegen.models.EntityBan;
import com.codegen.models.Error;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BanApi
 */
@Disabled
public class BanApiTest {

    private final BanApi api = new BanApi();

    /**
     * Deletes the entity: Ban
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void entitiesBanEntityIdDeleteTest() throws ApiException {
        String entityId = null;
        api.entitiesBanEntityIdDelete(entityId);
        // TODO: test validations
    }

    /**
     * Gets a single entity by identifier: Ban
     *
     * Gets a single entity by identifier
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void entitiesBanEntityIdGetTest() throws ApiException {
        String entityId = null;
        Boolean dynamicAttributes = null;
        Boolean returnNulls = null;
        String fetchPlan = null;
        EntityBan response = api.entitiesBanEntityIdGet(entityId, dynamicAttributes, returnNulls, fetchPlan);
        // TODO: test validations
    }

    /**
     * Updates the entity: Ban
     *
     * Updates the entity. Only fields that are passed in the JSON object (the request body) are updated.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void entitiesBanEntityIdPutTest() throws ApiException {
        String entityId = null;
        EntityBan entityBan = null;
        EntityBan response = api.entitiesBanEntityIdPut(entityId, entityBan);
        // TODO: test validations
    }

    /**
     * Gets a list of entities: Ban
     *
     * Gets a list of entities
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void entitiesBanGetTest() throws ApiException {
        Boolean returnCount = null;
        String offset = null;
        String limit = null;
        String sort = null;
        Boolean dynamicAttributes = null;
        Boolean returnNulls = null;
        String fetchPlan = null;
        List<EntityBan> response = api.entitiesBanGet(returnCount, offset, limit, sort, dynamicAttributes, returnNulls, fetchPlan);
        // TODO: test validations
    }

    /**
     * Creates new entity: Ban
     *
     * The method expects a JSON with entity object in the request body. The entity object may contain references to other entities.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void entitiesBanPostTest() throws ApiException {
        EntityBan entityBan = null;
        EntityBan response = api.entitiesBanPost(entityBan);
        // TODO: test validations
    }

    /**
     * Find entities by filter conditions: Ban
     *
     * Finds entities by filter conditions. The filter is defined by JSON object that is passed as URL parameter.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void entitiesBanSearchGetTest() throws ApiException {
        String filter = null;
        Boolean returnCount = null;
        String offset = null;
        String limit = null;
        String sort = null;
        Boolean dynamicAttributes = null;
        Boolean returnNulls = null;
        String fetchPlan = null;
        List<EntityBan> response = api.entitiesBanSearchGet(filter, returnCount, offset, limit, sort, dynamicAttributes, returnNulls, fetchPlan);
        // TODO: test validations
    }

    /**
     * Find entities by filter conditions: Ban
     *
     * Finds entities by filter conditions. The filter is defined by JSON object that is passed in body.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void entitiesBanSearchPostTest() throws ApiException {
        EntitiesDynatCategorySearchPostRequest entitiesDynatCategorySearchPostRequest = null;
        List<EntityBan> response = api.entitiesBanSearchPost(entitiesDynatCategorySearchPostRequest);
        // TODO: test validations
    }

}
