/*
 * Project REST API
 * Generated REST API documentation
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codegen.api;

import com.codegen.ApiException;
import com.codegen.models.EntitiesDynatCategorySearchPostRequest;
import com.codegen.models.EntityUser;
import com.codegen.models.Error;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserApi
 */
@Disabled
public class UserApiTest {

    private final UserApi api = new UserApi();

    /**
     * Deletes the entity: User
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void entitiesUserEntityIdDeleteTest() throws ApiException {
        String entityId = null;
        api.entitiesUserEntityIdDelete(entityId);
        // TODO: test validations
    }

    /**
     * Gets a single entity by identifier: User
     *
     * Gets a single entity by identifier
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void entitiesUserEntityIdGetTest() throws ApiException {
        String entityId = null;
        Boolean dynamicAttributes = null;
        Boolean returnNulls = null;
        String fetchPlan = null;
        EntityUser response = api.entitiesUserEntityIdGet(entityId, dynamicAttributes, returnNulls, fetchPlan);
        // TODO: test validations
    }

    /**
     * Updates the entity: User
     *
     * Updates the entity. Only fields that are passed in the JSON object (the request body) are updated.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void entitiesUserEntityIdPutTest() throws ApiException {
        String entityId = null;
        EntityUser entityUser = null;
        EntityUser response = api.entitiesUserEntityIdPut(entityId, entityUser);
        // TODO: test validations
    }

    /**
     * Gets a list of entities: User
     *
     * Gets a list of entities
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void entitiesUserGetTest() throws ApiException {
        Boolean returnCount = null;
        String offset = null;
        String limit = null;
        String sort = null;
        Boolean dynamicAttributes = null;
        Boolean returnNulls = null;
        String fetchPlan = null;
        List<EntityUser> response = api.entitiesUserGet(returnCount, offset, limit, sort, dynamicAttributes, returnNulls, fetchPlan);
        // TODO: test validations
    }

    /**
     * Creates new entity: User
     *
     * The method expects a JSON with entity object in the request body. The entity object may contain references to other entities.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void entitiesUserPostTest() throws ApiException {
        EntityUser entityUser = null;
        EntityUser response = api.entitiesUserPost(entityUser);
        // TODO: test validations
    }

    /**
     * Find entities by filter conditions: User
     *
     * Finds entities by filter conditions. The filter is defined by JSON object that is passed as URL parameter.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void entitiesUserSearchGetTest() throws ApiException {
        String filter = null;
        Boolean returnCount = null;
        String offset = null;
        String limit = null;
        String sort = null;
        Boolean dynamicAttributes = null;
        Boolean returnNulls = null;
        String fetchPlan = null;
        List<EntityUser> response = api.entitiesUserSearchGet(filter, returnCount, offset, limit, sort, dynamicAttributes, returnNulls, fetchPlan);
        // TODO: test validations
    }

    /**
     * Find entities by filter conditions: User
     *
     * Finds entities by filter conditions. The filter is defined by JSON object that is passed in body.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void entitiesUserSearchPostTest() throws ApiException {
        EntitiesDynatCategorySearchPostRequest entitiesDynatCategorySearchPostRequest = null;
        List<EntityUser> response = api.entitiesUserSearchPost(entitiesDynatCategorySearchPostRequest);
        // TODO: test validations
    }

}
