/*
 * Project REST API
 * Generated REST API documentation
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codegen.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EntityAuditEntitySnapshot
 */
public class EntityAuditEntitySnapshotTest {
    private final EntityAuditEntitySnapshot model = new EntityAuditEntitySnapshot();

    /**
     * Model tests for EntityAuditEntitySnapshot
     */
    @Test
    public void testEntityAuditEntitySnapshot() {
        // TODO: test EntityAuditEntitySnapshot
    }

    /**
     * Test the property 'entityName'
     */
    @Test
    public void entityNameTest() {
        // TODO: test entityName
    }

    /**
     * Test the property 'instanceName'
     */
    @Test
    public void instanceNameTest() {
        // TODO: test instanceName
    }

    /**
     * Test the property 'snapshotXml'
     */
    @Test
    public void snapshotXmlTest() {
        // TODO: test snapshotXml
    }

    /**
     * Test the property 'snapshotDate'
     */
    @Test
    public void snapshotDateTest() {
        // TODO: test snapshotDate
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'fetchPlanXml'
     */
    @Test
    public void fetchPlanXmlTest() {
        // TODO: test fetchPlanXml
    }

    /**
     * Test the property 'entityMetaClass'
     */
    @Test
    public void entityMetaClassTest() {
        // TODO: test entityMetaClass
    }

    /**
     * Test the property 'authorUsername'
     */
    @Test
    public void authorUsernameTest() {
        // TODO: test authorUsername
    }

    /**
     * Test the property 'sysTenantId'
     */
    @Test
    public void sysTenantIdTest() {
        // TODO: test sysTenantId
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
