/*
 * Project REST API
 * Generated REST API documentation
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codegen.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EntitiesDynatCategorySearchPostRequest
 */
public class EntitiesDynatCategorySearchPostRequestTest {
    private final EntitiesDynatCategorySearchPostRequest model = new EntitiesDynatCategorySearchPostRequest();

    /**
     * Model tests for EntitiesDynatCategorySearchPostRequest
     */
    @Test
    public void testEntitiesDynatCategorySearchPostRequest() {
        // TODO: test EntitiesDynatCategorySearchPostRequest
    }

    /**
     * Test the property 'filter'
     */
    @Test
    public void filterTest() {
        // TODO: test filter
    }

    /**
     * Test the property 'dynamicAttributes'
     */
    @Test
    public void dynamicAttributesTest() {
        // TODO: test dynamicAttributes
    }

    /**
     * Test the property 'returnCount'
     */
    @Test
    public void returnCountTest() {
        // TODO: test returnCount
    }

    /**
     * Test the property 'offset'
     */
    @Test
    public void offsetTest() {
        // TODO: test offset
    }

    /**
     * Test the property 'returnNulls'
     */
    @Test
    public void returnNullsTest() {
        // TODO: test returnNulls
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'sort'
     */
    @Test
    public void sortTest() {
        // TODO: test sort
    }

    /**
     * Test the property 'fetchPlan'
     */
    @Test
    public void fetchPlanTest() {
        // TODO: test fetchPlan
    }

}
