/*
 * Project REST API
 * Generated REST API documentation
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codegen.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EntityDynatCategory
 */
public class EntityDynatCategoryTest {
    private final EntityDynatCategory model = new EntityDynatCategory();

    /**
     * Model tests for EntityDynatCategory
     */
    @Test
    public void testEntityDynatCategory() {
        // TODO: test EntityDynatCategory
    }

    /**
     * Test the property 'entityName'
     */
    @Test
    public void entityNameTest() {
        // TODO: test entityName
    }

    /**
     * Test the property 'instanceName'
     */
    @Test
    public void instanceNameTest() {
        // TODO: test instanceName
    }

    /**
     * Test the property 'localeNames'
     */
    @Test
    public void localeNamesTest() {
        // TODO: test localeNames
    }

    /**
     * Test the property 'updatedBy'
     */
    @Test
    public void updatedByTest() {
        // TODO: test updatedBy
    }

    /**
     * Test the property 'entityType'
     */
    @Test
    public void entityTypeTest() {
        // TODO: test entityType
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'deletedBy'
     */
    @Test
    public void deletedByTest() {
        // TODO: test deletedBy
    }

    /**
     * Test the property 'special'
     */
    @Test
    public void specialTest() {
        // TODO: test special
    }

    /**
     * Test the property 'deleteTs'
     */
    @Test
    public void deleteTsTest() {
        // TODO: test deleteTs
    }

    /**
     * Test the property 'isDefault'
     */
    @Test
    public void isDefaultTest() {
        // TODO: test isDefault
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'createTs'
     */
    @Test
    public void createTsTest() {
        // TODO: test createTs
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'updateTs'
     */
    @Test
    public void updateTsTest() {
        // TODO: test updateTs
    }

}
