/*
 * Project REST API
 * Generated REST API documentation
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codegen.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ServicesAuthenticationLoginWithEmailPostRequest
 */
public class ServicesAuthenticationLoginWithEmailPostRequestTest {
    private final ServicesAuthenticationLoginWithEmailPostRequest model = new ServicesAuthenticationLoginWithEmailPostRequest();

    /**
     * Model tests for ServicesAuthenticationLoginWithEmailPostRequest
     */
    @Test
    public void testServicesAuthenticationLoginWithEmailPostRequest() {
        // TODO: test ServicesAuthenticationLoginWithEmailPostRequest
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

}
