/*
 * Project REST API
 * Generated REST API documentation
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codegen.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ServicesAuthenticationLoginWithCustomIdPostRequest
 */
public class ServicesAuthenticationLoginWithCustomIdPostRequestTest {
    private final ServicesAuthenticationLoginWithCustomIdPostRequest model = new ServicesAuthenticationLoginWithCustomIdPostRequest();

    /**
     * Model tests for ServicesAuthenticationLoginWithCustomIdPostRequest
     */
    @Test
    public void testServicesAuthenticationLoginWithCustomIdPostRequest() {
        // TODO: test ServicesAuthenticationLoginWithCustomIdPostRequest
    }

    /**
     * Test the property 'customId'
     */
    @Test
    public void customIdTest() {
        // TODO: test customId
    }

    /**
     * Test the property 'createIfNotExists'
     */
    @Test
    public void createIfNotExistsTest() {
        // TODO: test createIfNotExists
    }

}
