/*
 * Project REST API
 * Generated REST API documentation
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codegen.models;

import com.codegen.models.EntityUser;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ServicesAuthenticationAddUsernamePasswordPostRequest
 */
public class ServicesAuthenticationAddUsernamePasswordPostRequestTest {
    private final ServicesAuthenticationAddUsernamePasswordPostRequest model = new ServicesAuthenticationAddUsernamePasswordPostRequest();

    /**
     * Model tests for ServicesAuthenticationAddUsernamePasswordPostRequest
     */
    @Test
    public void testServicesAuthenticationAddUsernamePasswordPostRequest() {
        // TODO: test ServicesAuthenticationAddUsernamePasswordPostRequest
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

}
